language: c
sudo: required

services:
  - docker

env:
  matrix:
    - IMAGE_NAME=ocaml/opam2:4.03
    - IMAGE_NAME=ocaml/opam2:4.07

before_install:
  - docker pull $IMAGE_NAME

script:
  - docker run --privileged -v `pwd`:/mnt:ro $IMAGE_NAME /mnt/.travis.sh
