language: c
sudo: required

services:
  - docker

env:
  matrix:
    - IMAGE_NAME=ocaml/opam:alpine_ocaml-4.02.3
    - IMAGE_NAME=ocaml/opam:alpine_ocaml-4.06.0_flambda

before_install:
  - docker pull $IMAGE_NAME

script:
  - docker run --privileged -v `pwd`:/mnt:ro $IMAGE_NAME /mnt/pkg/ci.sh
